version: '2'
services:
  tomcat:
    expose:
      - "9090"
    build: ../../tomcat
  httpd:
    volumes:
      - ./logs:/var/log/apache2
    ports:
      - "${HOST_HTTP_PORT}:80"
      - "${HOST_HTTPS_PORT}:443"
    build: ../../httpd
